export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR   = 'LOGIN_ERROR'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR   = 'REGISTER_ERROR'

export const EDIT_REQUEST = 'EDIT_REQUEST'
export const EDIT_SUCCESS = 'EDIT_SUCCESS'
export const EDIT_ERROR   = 'EDIT_ERROR'

export const DELETE_REQUEST = 'DELETE_REQUEST'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const DELETE_ERROR   = 'DELETE_ERROR'

export const REQUEST_GET_BARANG = 'REQUEST_GET_BARAN'
export const SUCCESS_GET_BARANG = 'SUCCESS_GET_BARANG'
export const ERROR_GET_BARANG   = 'SUCCESS_GET_BARANG'

export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_ERROR   = 'SEARCH_ERROR'

export const GET_ITEM_BY_ID_REQUEST = 'GET_ITEM_BY_ID_REQUEST'
export const GET_ITEM_BY_ID_SUCCESS = 'GET_ITEM_BY_ID_SUCCESS'
export const GET_ITEM_BY_ID_ERROR   = 'GET_ITEM_BY_ID_ERROR'

export const KD_PRODUK_REQUEST  = 'KD_PRODUK_REQUEST'
export const KD_PRODUK_SUCCESS  = 'KD_PRODUK_SUCCESS'
export const KD_PRODUK_ERROR    = 'KD_PRODUK_ERROR'

export const KD_SATUAN_REQUEST  = 'KD_SATUAN_REQUEST'
export const KD_SATUAN_SUCCESS  = 'KD_SATUAN_SUCCESS'
export const KD_SATUAN_ERROR    = 'KD_SATUAN_ERROR'